services:
    warble_media_phoenix.form.registration_factory:
        class: WarbleMedia\PhoenixBundle\Form\FormFactory
        arguments:
            - '@form.factory'
            - '%warble_media_phoenix.forms.registration.name%'
            - '%warble_media_phoenix.forms.registration.type%'
            - '%warble_media_phoenix.forms.registration.validation_groups%'

    warble_media_phoenix.form.registration_form_type:
        class: WarbleMedia\PhoenixBundle\Form\RegistrationFormType
        arguments:
            - '%warble_media_phoenix.models.user_class%'
        tags:
            - { name: form.type, alias: WarbleMedia\PhoenixBundle\Form\RegistrationFormType }

    warble_media_phoenix.form.resetting_factory:
        class: WarbleMedia\PhoenixBundle\Form\FormFactory
        arguments:
            - '@form.factory'
            - '%warble_media_phoenix.forms.resetting.name%'
            - '%warble_media_phoenix.forms.resetting.type%'
            - '%warble_media_phoenix.forms.resetting.validation_groups%'

    warble_media_phoenix.form.resetting_form_type:
        class: WarbleMedia\PhoenixBundle\Form\ResettingFormType
        arguments:
            - '%warble_media_phoenix.models.user_class%'
        tags:
            - { name: form.type, alias: WarbleMedia\PhoenixBundle\Form\ResettingFormType }

    warble_media_phoenix.form.profile_factory:
        class: WarbleMedia\PhoenixBundle\Form\FormFactory
        arguments:
            - '@form.factory'
            - '%warble_media_phoenix.forms.profile.name%'
            - '%warble_media_phoenix.forms.profile.type%'
            - '%warble_media_phoenix.forms.profile.validation_groups%'

    warble_media_phoenix.form.profile_form_type:
        class: WarbleMedia\PhoenixBundle\Form\ProfileFormType
        arguments:
            - '%warble_media_phoenix.models.user_class%'
        tags:
            - { name: form.type, alias: WarbleMedia\PhoenixBundle\Form\ProfileFormType }

    warble_media_phoenix.form.profile_photo_factory:
        class: WarbleMedia\PhoenixBundle\Form\FormFactory
        arguments:
            - '@form.factory'
            - '%warble_media_phoenix.forms.profile_photo.name%'
            - '%warble_media_phoenix.forms.profile_photo.type%'

    warble_media_phoenix.form.profile_photo_form_type:
        class: WarbleMedia\PhoenixBundle\Form\ProfilePhotoFormType
        tags:
            - { name: form.type, alias: WarbleMedia\PhoenixBundle\Form\ProfilePhotoFormType }

    warble_media_phoenix.form.change_password_factory:
        class: WarbleMedia\PhoenixBundle\Form\FormFactory
        arguments:
            - '@form.factory'
            - '%warble_media_phoenix.forms.change_password.name%'
            - '%warble_media_phoenix.forms.change_password.type%'
            - '%warble_media_phoenix.forms.change_password.validation_groups%'

    warble_media_phoenix.form.change_password_form_type:
        class: WarbleMedia\PhoenixBundle\Form\ChangePasswordFormType
        arguments:
            - '%warble_media_phoenix.models.user_class%'
        tags:
            - { name: form.type, alias: WarbleMedia\PhoenixBundle\Form\ChangePasswordFormType }

    warble_media_phoenix.form.plan_choice_type:
        class: WarbleMedia\PhoenixBundle\Form\PlanChoiceType
        arguments:
            - '@warble_media_phoenix.billing.plan_manager'
        tags:
            - { name: form.type, alias: WarbleMedia\PhoenixBundle\Form\PlanChoiceType }

    warble_media_phoenix.form.subscription_factory:
        class: WarbleMedia\PhoenixBundle\Form\FormFactory
        arguments:
            - '@form.factory'
            - '%warble_media_phoenix.forms.subscription.name%'
            - '%warble_media_phoenix.forms.subscription.type%'

    warble_media_phoenix.form.subscription_form:
        class: WarbleMedia\PhoenixBundle\Form\SubscriptionType
        tags:
            - { name: form.type, alias: WarbleMedia\PhoenixBundle\Form\SubscriptionType }

    warble_media_phoenix.form.payment_method_form:
        class: WarbleMedia\PhoenixBundle\Form\PaymentMethodType
        tags:
            - { name: form.type, alias: WarbleMedia\PhoenixBundle\Form\PaymentMethodType }
