services:
    warble_media_phoenix.event_listener.authentication_subscriber:
        class: WarbleMedia\PhoenixBundle\EventListener\AuthenticationSubscriber
        arguments:
            - '@warble_media_phoenix.security.login_manager'
            - '%warble_media_phoenix.firewall_name%'
        tags:
            - { name: kernel.event_subscriber }

    warble_media_phoenix.event_listener.last_login_subscriber:
        class: WarbleMedia\PhoenixBundle\EventListener\LastLoginSubscriber
        arguments:
            - '@warble_media_phoenix.model.user_manager'
        tags:
            - { name: kernel.event_subscriber }

    warble_media_phoenix.event_listener.resetting_subscriber:
        class: WarbleMedia\PhoenixBundle\EventListener\ResettingSubscriber
        arguments:
            - '@router'
            - '%warble_media_phoenix.resetting.token_ttl%'
        tags:
            - { name: kernel.event_subscriber }

    warble_media_phoenix.event_listener.ormmapped_super_class_subscriber:
        class: WarbleMedia\PhoenixBundle\EventListener\ORMMappedSuperClassSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    warble_media_phoenix.event_listener.sync_stripe_customer_subscriber:
        class: WarbleMedia\PhoenixBundle\EventListener\SyncStripeCustomerSubscriber
        arguments:
            - '@warble_media_phoenix.billing.payment_processor'
        tags:
            - { name: kernel.event_subscriber }

    warble_media_phoenix.event_listener.stripe_webhook_subscriber:
        class: WarbleMedia\PhoenixBundle\EventListener\StripeWebhookSubscriber
        arguments:
            - '@logger'
        tags:
            - { name: kernel.event_subscriber }

    warble_media_phoenix.event_listener.stripe_subscription_webhook_subscriber:
        class: WarbleMedia\PhoenixBundle\EventListener\StripeSubscriptionWebhookSubscriber
        arguments:
            - '@warble_media_phoenix.model.customer_manager'
            - '@warble_media_phoenix.model.subscription_manager'
        tags:
            - { name: kernel.event_subscriber }

    warble_media_phoenix.event_listener.stripe_invoice_webhook_subscriber:
        class: WarbleMedia\PhoenixBundle\EventListener\StripeInvoiceWebhookSubscriber
        arguments:
            - '@warble_media_phoenix.model.customer_manager'
            - '@warble_media_phoenix.model.invoice_manager'
            - '%warble_media_phoenix.stripe.secret_key%'
        tags:
            - { name: kernel.event_subscriber }
