services:
    warble_media_phoenix.event_listener.authentication_subscriber:
        class: WarbleMedia\PhoenixBundle\EventListener\AuthenticationSubscriber
        arguments:
            - '@warble_media_phoenix.security.login_manager'
            - '%warble_media_phoenix.firewall_name%'
        tags:
            - { name: kernel.event_subscriber }

    warble_media_phoenix.event_listener.last_login_subscriber:
    	class: WarbleMedia\PhoenixBundle\EventListener\LastLoginSubscriber
    	arguments:
    	    - '@warble_media_phoenix.model.user_manager'
    	tags:
    		- { name: kernel.event_subscriber }
