warble_media_phoenix_register:
    path:     /register
    methods:  [GET, POST]
    defaults: { _controller: WarbleMediaPhoenixBundle:Registration:register }

warble_media_phoenix_register_confirmed:
    path:     /register/confirmed
    methods:  [GET]
    defaults: { _controller: WarbleMediaPhoenixBundle:Registration:confirmed }
