services:
    # TODO: Allow custom implementation
    warble_media_phoenix.model.user_manager:
        class: WarbleMedia\PhoenixBundle\Model\UserManager
        arguments:
            - '@security.encoder_factory'
            - '@doctrine.orm.entity_manager'
            - '%warble_media_phoenix.models.user_class%'

    warble_media_phoenix.security.registration_manager:
        class: WarbleMedia\PhoenixBundle\Security\RegistrationManager
        arguments:
            - '@warble_media_phoenix.model.user_manager'

    warble_media_phoenix.security.login_manager:
        class: WarbleMedia\PhoenixBundle\Security\LoginManager
        arguments:
            - '@security.user_checker'
            - '@request_stack'
            - '@security.token_storage'
            - '@security.authentication.session_strategy'
            - '@service_container'

    warble_media_phoenix.twig_extension.phoenix_extension:
        class: WarbleMedia\PhoenixBundle\Twig\Extension\PhoenixExtension
        tags:
            - { name: twig.extension }
