services:
    # TODO: Allow custom implementation
    warble_media_phoenix.model.user_manager:
        alias: 'warble_media_phoenix.model.customer_manager'

    warble_media_phoenix.model.user_photo_manager:
        class: WarbleMedia\PhoenixBundle\Model\UserPhotoManager
        arguments:
            - '%warble_media_phoenix.profile_photos.base_url%'
            - '%warble_media_phoenix.profile_photos.base_path%'

    warble_media_phoenix.model.customer_manager:
        class: WarbleMedia\PhoenixBundle\Model\CustomerManager
        arguments:
            - '@security.encoder_factory'
            - '@doctrine.orm.entity_manager'
            - '@warble_media_phoenix.billing.payment_processor'
            - '%warble_media_phoenix.trial_days%'
            - '%warble_media_phoenix.models.customer_class%'

    warble_media_phoenix.model.subscription_manager:
        class: WarbleMedia\PhoenixBundle\Model\SubscriptionManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@warble_media_phoenix.billing.payment_processor'
            - '%warble_media_phoenix.models.subscription_class%'

    warble_media_phoenix.model.invoice_manager:
        class: WarbleMedia\PhoenixBundle\Model\InvoiceManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@warble_media_phoenix.billing.payment_processor'
            - '%warble_media_phoenix.models.invoice_class%'

    warble_media_phoenix.model.metrics_manager:
        class: WarbleMedia\PhoenixBundle\Model\MetricsManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%warble_media_phoenix.models.metrics_class%'

    warble_media_phoenix.performance.indicators:
        class: WarbleMedia\PhoenixBundle\Performance\PerformanceIndicators
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@warble_media_phoenix.billing.plan_manager'

    warble_media_phoenix.security.registration_manager:
        class: WarbleMedia\PhoenixBundle\Security\RegistrationManager
        arguments:
            - '@warble_media_phoenix.model.user_manager'

    warble_media_phoenix.security.login_manager:
        class: WarbleMedia\PhoenixBundle\Security\LoginManager
        arguments:
            - '@security.user_checker'
            - '@request_stack'
            - '@security.token_storage'
            - '@security.authentication.session_strategy'
            - '@service_container'

    warble_media_phoenix.mailer:
        class: WarbleMedia\PhoenixBundle\Mailer\Mailer
        arguments:
            - '@twig'
            - '@swiftmailer.mailer'
            - '@service_container'

    warble_media_phoenix.billing.plan_manager:
        class: WarbleMedia\PhoenixBundle\Billing\PlanManager

    warble_media_phoenix.billing.payment_processor:
        class: WarbleMedia\PhoenixBundle\Billing\PaymentProcessor
        arguments:
            - '%warble_media_phoenix.stripe.secret_key%'

    warble_media_phoenix.util.token_generator:
        class: WarbleMedia\PhoenixBundle\Util\TokenGenerator

    warble_media_phoenix.twig.phoenix_variable:
        class: WarbleMedia\PhoenixBundle\Twig\PhoenixVariable
        arguments:
            - '@service_container'

    warble_media_phoenix.templating_helper.money_helper:
        class: WarbleMedia\PhoenixBundle\Templating\Helper\MoneyHelper
        arguments:
            - '%warble_media_phoenix.billing.currency%'
            - '%warble_media_phoenix.default_locale%'

    warble_media_phoenix.templating_helper.plan_helper:
        class: WarbleMedia\PhoenixBundle\Templating\Helper\PlanHelper
        arguments:
            - '@warble_media_phoenix.billing.plan_manager'

    warble_media_phoenix.twig_extension.money_extension:
        class: WarbleMedia\PhoenixBundle\Twig\Extension\MoneyExtension
        arguments:
            - '@warble_media_phoenix.templating_helper.money_helper'
        tags:
            - { name: twig.extension }

    warble_media_phoenix.twig_extension.plan_extension:
        class: WarbleMedia\PhoenixBundle\Twig\Extension\PlanExtension
        arguments:
            - '@warble_media_phoenix.templating_helper.plan_helper'
        tags:
            - { name: twig.extension }
