services:
    # TODO: Allow custom implementation
    warble_media_phoenix.model.user_manager:
        class: WarbleMedia\PhoenixBundle\Model\UserManager
        arguments: ['%warble_media_phoenix.models.user_class%']
