warble_media_phoenix_developer:
    path:     /
    methods:  [GET]
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: warble_media_phoenix_developer_metrics }

warble_media_phoenix_developer_metrics:
    path:     /metrics
    methods:  [GET]
    defaults: { _controller: WarbleMediaPhoenixBundle:Developer:metrics }

warble_media_phoenix_developer_users:
    path:     /users
    methods:  [GET]
    defaults: { _controller: WarbleMediaPhoenixBundle:Developer:users }

warble_media_phoenix_developer_user_profile:
    path:     /users/{id}
    methods:  [GET]
    defaults: { _controller: WarbleMediaPhoenixBundle:Developer:userProfile }
